#!/usr/bin/env node
/**
 * Wrap dist/style.css in the SoftAP assets.cpp R-string.
 * Source of truth for CSS build: input.css + pages/*.cpp class names.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const cssPath = path.join(__dirname, "dist", "style.css");
const outPath = path.join(__dirname, "..", "core", "assets.cpp");

if (!fs.existsSync(cssPath)) {
  console.error(`embed: missing ${cssPath} — run build:css first`);
  process.exit(1);
}

const css = fs.readFileSync(cssPath, "utf8").trim();
if (css.includes(")chitram_css")) {
  console.error("embed: CSS contains R-string terminator )chitram_css");
  process.exit(1);
}

const cpp = `#include "registry.h"

// SoftAP stylesheet — generated by ap_server/ui (npm run build). Do not edit by hand.
static const char kStyleCss[] = R"chitram_css(
${css}
)chitram_css";

static void handleStyle(WebServer &server) {
  apSendBody(server, "text/css; charset=utf-8", kStyleCss);
}

static const ApGetReg kAssets[] = {
    {"/style.css", handleStyle},
};
static ApAutoRegister regAssets(kAssets, 1);
`;

fs.writeFileSync(outPath, cpp);
console.log(`embed: wrote ${outPath} (${css.length} css bytes)`);
